require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'docker/**/*'
    - 'node_modules/**/*'
    - 'sample_data/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - test/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/**/*'
